
- name: Setup base system
  hosts: master
  gather_facts: yes
  become: false
  become_method: sudo
  vars_files:
    - config.yml

  roles:
    - base
    - role: geerlingguy.ntp
      ntp_manage_config: true
      ntp_servers: [
        clock.sjc.he.net,
        clock.fmt.he.net,
        clock.nyc.he.net
      ]
      become: yes
    - role: geerlingguy.swap
      swap_file_size_mb: '2048'
      become: yes
  # environment:
  #   http_proxy: "{{ lookup('env','http_proxy') }}"
  #   https_proxy: "{{ lookup('env','https_proxy') }}"
